# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ba7965dff612b3a690de2f50b87ad0e0ea80494c3fe17717a5e43628e7e8b54ea8b91134405493c196e659e8c1c92e03a56402faddb20c7213f9c65711978dcd

test:
  secret_key_base: ba1f2e526035ed02374786ef84ed0ecd58ff5bcd28bb1008e811b788a5fc125f9745035f9311d3175af0c614b16d98cab0cb9cc52a16d1e78a688793b60738c5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
